FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o /app/ingestor ./cmd/ingestor

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/ingestor .

CMD ["./ingestor"]
