FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o /app/api ./cmd/api

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/api .

EXPOSE 8080
CMD ["./api"]
